{{- if empty .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: ghost
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.ghostPassword }}
  ghost-password: {{ default "" .Values.ghostPassword | b64enc | quote }}
  {{- else }}
  ghost-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.smtpPassword }}
  smtp-password: {{ default "" .Values.smtpPassword | b64enc | quote }}
  {{- end }}
{{- end }}
